services:
  postgresql:
    image: repo.iris.tools/fabric/testdb/postgres:15.3-20240621.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin1234"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: test
    volumes:
      - /DATA/db-data/postgres:/var/lib/postgresql/data
  mysql:
    image: repo.iris.tools/fabric/testdb/mysql:8.0-20240621.0
    ports:
      - "5307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin1234"
      MYSQL_DATABASE: test
    volumes:
      - /DATA/db-data/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --sql_mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
  mariadb:
    image: repo.iris.tools/fabric/testdb/mariadb:10.9.7-20240621.0
    ports:
      - "5306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin1234"
      MYSQL_DATABASE: test
    volumes:
      - /DATA/db-data/mariadb:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --sql_mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
