create table sampledata_chart_22
(
    link   text,
    id     text,
    color  text,
    radius integer
);

alter table sampledata_chart_22
    owner to postgres;

INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Proto Indo-European', '#304FFE', 30);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Balto-Slavic', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Germanic', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Celtic', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Italic', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Hellenic', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Anatolian', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Indo-Iranian', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Tocharian', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Indo-Iranian', 'Dardic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Indo-Iranian', 'Indic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Indo-Iranian', 'Iranian', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Iranian', 'Old Persian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Persian', 'Middle Persian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Indic', 'Sanskrit', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Italic', 'Osco-Umbrian', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Italic', 'Latino-Faliscan', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latino-Faliscan', 'Latin', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Celtic', 'Brythonic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Celtic', 'Goidelic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Germanic', 'North Germanic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Germanic', 'West Germanic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Germanic', 'East Germanic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('North Germanic', 'Old Norse', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('North Germanic', 'Old Swedish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('North Germanic', 'Old Danish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Germanic', 'Old English', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Germanic', 'Old Frisian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Germanic', 'Old Dutch', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Germanic', 'Old Low German', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Germanic', 'Old High German', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Norse', 'Old Icelandic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Norse', 'Old Norwegian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Norwegian', 'Middle Norwegian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Swedish', 'Middle Swedish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Danish', 'Middle Danish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old English', 'Middle English', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Dutch', 'Middle Dutch', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Low German', 'Middle Low German', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old High German', 'Middle High German', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Balto-Slavic', 'Baltic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Balto-Slavic', 'Slavic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Slavic', 'East Slavic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Slavic', 'West Slavic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Slavic', 'South Slavic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Phrygian', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Armenian', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Albanian', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Proto Indo-European', 'Thracian', '#80D8FF', 20);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Tocharian', 'Tocharian A', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Tocharian', 'Tocharian B', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Anatolian', 'Hittite', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Anatolian', 'Palaic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Anatolian', 'Luwic', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Anatolian', 'Lydian', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Iranian', 'Balochi', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Iranian', 'Kurdish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Iranian', 'Pashto', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Iranian', 'Sogdian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Persian', 'Pahlavi', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Persian', 'Persian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Hellenic', 'Greek', '#43A047', 10);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Dardic', 'Dard', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Sindhi', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Romani', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Urdu', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Hindi', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Bihari', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Assamese', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Bengali', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Marathi', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Gujarati', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Punjabi', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Sanskrit', 'Sinhalese', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Osco-Umbrian', 'Umbrian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Osco-Umbrian', 'Oscan', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latino-Faliscan', 'Faliscan', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latin', 'Portugese', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latin', 'Spanish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latin', 'French', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latin', 'Romanian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latin', 'Italian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latin', 'Catalan', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latin', 'Franco-Provençal', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Latin', 'Rhaeto-Romance', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Brythonic', 'Welsh', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Brythonic', 'Breton', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Brythonic', 'Cornish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Brythonic', 'Cuymbric', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Goidelic', 'Modern Irish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Goidelic', 'Scottish Gaelic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Goidelic', 'Manx', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('East Germanic', 'Gothic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Low German', 'Low German', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle High German', '(High) German', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle High German', 'Yiddish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle English', 'English', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Dutch', 'Hollandic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Dutch', 'Flemish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Dutch', 'Dutch', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Dutch', 'Limburgish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Dutch', 'Brabantian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Dutch', 'Rhinelandic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Frisian', 'Frisian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Danish', 'Danish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Swedish', 'Swedish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Middle Norwegian', 'Norwegian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Norse', 'Faroese', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Old Icelandic', 'Icelandic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Baltic', 'Old Prussian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Baltic', 'Lithuanian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('Baltic', 'Latvian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Slavic', 'Polish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Slavic', 'Slovak', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Slavic', 'Czech', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('West Slavic', 'Wendish', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('East Slavic', 'Bulgarian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('East Slavic', 'Old Church Slavonic', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('East Slavic', 'Macedonian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('East Slavic', 'Serbo-Croatian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('East Slavic', 'Slovene', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('South Slavic', 'Russian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('South Slavic', 'Ukrainian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('South Slavic', 'Belarusian', '#FFC400', 5);
INSERT INTO public.sampledata_chart_22 (link, id, color, radius) VALUES ('South Slavic', 'Rusyn', '#FFC400', 5);
